title: Richard Lung Wicaksono # your name (or website title) here
logo: "IMG_0851.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I have 2+ years of coding, including languages such as Python, Java, and C++. Received an Associate's Degree in Arts – Direct Transfer Agreement at Shoreline Community College and graduated with Honors (3.73 GPA).
  <br><br>
  Currently a Junior at Seattle Pacific University pursuing a Bachelor's Degree of Science in Information Systems. My hobbies include watching and playing soccer, basketball, and badminton.
  <br><br>
  <a href="https://www.linkedin.com/in/richardlungw">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://www.github.com/richardlwspu14">View My GitHub Profile</a>
  
theme: jekyll-theme-minimal

google_analytics: UA-000000-0 # your Google Analytics tracking ID here
